[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  
[build.processing]
  skip_processing = false

[build.environment]
  NODE_VERSION = "16"

[functions.server]
  included_files = ["**"]
  node_bundler = "esbuild"
  external_node_modules = []
  timeout = 26

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
