/**
 * Email Service Module for Agent Smith
 * Handles sending emails with AI content and authentication links
 */
const { Resend } = require('resend');

// Initialize Resend client
const resend = new Resend(process.env.RESEND_API_KEY);

/**
 * Send a job completion email with AI content and authentication link
 * @param {Object} job - Job data from database
 * @param {Object} emailContent - Generated email content with subject and body
 * @param {string} signInLink - Authentication link generated by Supabase
 * @returns {Object} Email sending result
 */
async function sendJobCompletionEmail(job, emailContent, signInLink) {
  try {
    console.log(`[EmailService] Sending job completion email to ${job.email}`);
    
    // Create HTML email with proper structure for email clients
    const htmlContent = createEmailTemplate(job.name, emailContent.body, signInLink);
    
    // Send email through Resend
    const { data, error } = await resend.emails.send({
      from: process.env.RESEND_SENDER_EMAIL || 'Agent Smith <hello@agent-smith.com>',
      to: job.email,
      subject: emailContent.subject || 'Your Website Analysis + Account Access',
      html: htmlContent,
      // Optional fields
      text: htmlContent.replace(/<[^>]*>/g, ''), // Plain text version
      tags: [{
        name: "source",
        value: "agent_smith"
      }]
    });
    
    if (error) {
      console.error(`[EmailService] Error sending email:`, error);
      throw error;
    }
    
    console.log(`[EmailService] Email sent successfully, ID: ${data.id}`);
    return { success: true, emailId: data.id };
  } catch (error) {
    console.error(`[EmailService] Exception sending email:`, error);
    throw error;
  }
}

/**
 * Create a properly formatted HTML email template
 * @param {string} name - Recipient's name
 * @param {string} content - Email content (HTML)
 * @param {string} signInLink - Authentication link
 * @returns {string} Complete HTML email
 */
function createEmailTemplate(name, content, signInLink) {
  return `
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Your Personalized Agent Smith Analysis</title>
</head>
<body style="margin: 0; padding: 0; font-family: Arial, Helvetica, sans-serif; color: #000000;">
  <table border="0" cellpadding="0" cellspacing="0" width="100%">
    <tr>
      <td>
        <table align="center" border="0" cellpadding="0" cellspacing="0" width="600" style="border-collapse: collapse;">
          <tr>
            <td style="padding: 20px;">
              <!-- Email Header -->
              <table border="0" cellpadding="0" cellspacing="0" width="100%">
                <tr>
                  <td style="font-size: 24px; font-weight: bold; color: #000000; padding-bottom: 20px;">
                    Welcome to Agent Smith, ${name}!
                  </td>
                </tr>
                <tr>
                  <td style="padding-bottom: 15px; color: #000000;">
                    We've prepared a personalized analysis for you:
                  </td>
                </tr>
              </table>
              
              <!-- Personalized Content -->
              <table border="0" cellpadding="0" cellspacing="0" width="100%">
                <tr>
                  <td style="color: #000000;">
                    ${content}
                  </td>
                </tr>
              </table>
              
              <!-- Invitation Section -->
              <table border="0" cellpadding="0" cellspacing="0" width="100%">
                <tr>
                  <td style="padding-top: 30px; color: #000000;">
                    To access your Agent Smith dashboard and complete your account setup, please click the link below:
                  </td>
                </tr>
                <tr>
                  <td style="padding: 20px 0;">
                    <table border="0" cellpadding="0" cellspacing="0">
                      <tr>
                        <td style="background-color: #4CAF50; border-radius: 4px; text-align: center;">
                          <a href="${signInLink}" style="display: inline-block; padding: 12px 24px; color: #ffffff; text-decoration: none; font-weight: bold;">Access Dashboard</a>
                        </td>
                      </tr>
                    </table>
                  </td>
                </tr>
                <tr>
                  <td style="color: #000000;">
                    This link will expire in 24 hours. If you did not request this analysis, please ignore it.
                  </td>
                </tr>
              </table>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>
  `;
}

module.exports = {
  sendJobCompletionEmail
};
